name: 'holunder'
description: 'Sync Google Docs in a folder to local Markdowm files and commit them automatically'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Create dir
      shell: bash
      run: mkdir -p ${{ inputs.local_markdown_root_folder }}

    - name: holunder
      uses: ./.github/actions/holunder-docker
      with:
        ${{ toJSON(inputs) }}

    - name: check result
      shell: bash
      run: ls -la && ls -la ${{ inputs.local_markdown_root_folder }}

    - name: autocommit
      uses: stefanzweifel/git-auto-commit-action@v6
      with:
        ${{ toJSON(inputs) }}