name: 'holunder'
description: 'Sync Google Docs in a folder to local Markdowm files and commit them automatically'

inputs:
  holunder:
    description: 'Config inputs for holunder'
    type: string
    required: true
  autocommit:
    description: 'Config inputs for stefanzweifel/git-auto-commit-action@v6'
    type: string
    required: false
    default: '{}'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Create dir
      shell:
        mkdir -p ${{ fromJSON(config.holunder).local_markdown_root_folder }}

    - name: holunder
      uses: ./.github/actions/holunder-docker.yml
      with:
        ${{ config.holunder }}

    - name: check result
      run: ls -la && ls -la ${{ fromJSON(config.holunder).local_markdown_root_folder }}

    - name: autocommit
      uses: stefanzweifel/git-auto-commit-action@v6
      if: ${{ config.autocommit }} != '{}'
      with:
        ${{ config.holunder }}
        file_pattern: ${{ fromJSON(config.holunder).local_markdown_root_folder }}/