line-length = 100

[lint]
select = [
    # pyupgrade
    "UP",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true