name: Code checks

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: default

jobs:
  check:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    name: Check Python${{ matrix.python-version }}

    steps:
    - name: checkout current commit
      uses: actions/checkout@v4
      if: ${{ inputs.ref == 'default' }}

    - name: checkout main
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
      if: ${{ inputs.ref != 'default' }}

    - name: install python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: install dependencies
      run: |
        make requirements
        make requirements_dev

    - name: lint
      run: make lint

    - name: test
      run: make tests

    - name: codeql_init
      uses: github/codeql-action/init@v3
      with:
        languages: 'python'

    - name: codeql_analyze
      uses: github/codeql-action/analyze@v3
